global.data = { 
    utakmice:[
        { 
            id: 1,
            team1: "dinamo", 
            team2: "hajduk", 
            gol1: 10, 
            gol2: 0,
            played: true,
            comments: ["abcd", "bcde", "efgh"],
        }, 
        { 
            id: 2,
            team1: "gorica", 
            team2: "rijeka", 
            gol1: 1, 
            gol2: 5,
            played: true,
            comments: [],
        }, 
        { 
            id: 3,
            team1: "nk jazbina", 
            team2: "maroko", 
            gol1: 0, 
            gol2: 3,
            played: true,
            comments: [],
        }, 
        { 
            id: 4,
            team1: "granki", 
            team2: "senks", 
            gol1: 11, 
            gol2: 3,
            played: true,
            comments: [],
        }, 
        { 
            id: 5,
            team1: "netko", 
            team2: "netkog", 
            gol1: 0, 
            gol2: 0,
            played: false,
            comments: [],
        }, 
        { 
            id: 6,
            team1: "osijek", 
            team2: "ludogorec", 
            gol1: 0, 
            gol2: 0,
            played: false,
            comments: [],
        }, 
        { 
            id: 7,
            team1: "hajduk", 
            team2: "dinamo", 
            gol1: 0, 
            gol2: 0,
            played: false,
            comments: [],
        }
    ] 
}
